#!/bin/bash

openterminal="gnome-terminal"
openmath="gnome-terminal --tab -t math -- vim -S dev/.vimrc -p include/math/*.hpp src/math/*.cpp"
openwave="gnome-terminal --tab -t wave -- vim -S dev/.vimrc -p src/wave/*.cpp"
openui="gnome-terminal --tab -t ui -- vim -S dev/.vimrc -p src/ui/*.cpp"
openapp="gnome-terminal --tab -t app -- vim -S dev/.vimrc -p src/app/*.cpp"
openstyle="gnome-terminal --tab -t style -- vim -S dev/.vimrc -p res/styles/*.style"
openmain="gnome-terminal --tab -t main -- vim -S dev/.vimrc src/main.cpp"
openchanger="gnome-terminal --tab -t changer -- vim -S dev/.vimrc src/changer/*.cpp"

if [ $# -eq 0 ]
then
    $openterminal
    $openmath
    $openwave
    $openui
    $openapp
    $openstyle
    $openmain
fi

while [[ $# -gt 0 ]]
do
    case $1 in
        math)
            $openmath
            ;;
        wave)
            $openwave
            ;;
        ui)
            $openui
            ;;
        app)
            $openapp
            ;;
        main)
            $openmain
            ;;
        style)
            $openstyle
            ;;
        changer)
            $openchanger
            ;;
        make)
            $openterminal
            ;;
    esac
    shift 1
done

