#!/bin/bash

openterminal="gnome-terminal"
openmath="gnome-terminal --tab -t math -- vim -S dev/.vimrc -p src/math/*.cpp include/math/constants.h"
openwave="gnome-terminal --tab -t wave -- vim -S dev/.vimrc -p src/wave/*.cpp"
openui="gnome-terminal --tab -t ui -- vim -S dev/.vimrc -p src/ui/*.cpp"
openapp="gnome-terminal --tab -t app -- vim -S dev/.vimrc -p src/app/*.cpp"
openstyle="gnome-terminal --tab -t style -- vim -S dev/.vimrc -p res/styles/*.style"
openmain="gnome-terminal --tab -t main -- vim -S dev/.vimrc -p src/main.cpp"
openchange="gnome-terminal --tab -t changer -- vim -S dev/.vimrc -p src/change/*.cpp"
opentools="gnome-terminal --tab -t tools -- vim -S dev/.vimrc -p src/tools/*.cpp"
openwstream="gnome-terminal --tab -t wstream -- vim -S dev/.vimrc -p lib/Wstream/src/wstream/*.cpp"

while [[ $# -gt 0 ]]
do
    case $1 in
        math)
            $openmath
            ;;
        wave)
            $openwave
            ;;
        ui)
            $openui
            ;;
        app)
            $openapp
            ;;
        main)
            $openmain
            ;;
        style)
            $openstyle
            ;;
        change)
            $openchange
            ;;
        tools)
            $opentools
            ;;
        wstream)
            $openwstream
            ;;
        make)
            $openterminal
            ;;
    esac
    shift 1
done

